version: 2

env: &env
  GOOGLE_CLOUD_SDK_VERSION: 221.0.0
  GOOGLE_CLOUD_SDK_DOWNLOAD_PATH: /google-cloud-sdk

gitconfig: &gitconfig
  name: "Set .gitconfig"
  command: |
    echo "" > ~/.gitconfig
    git config --global url."https://github.com".insteadOf git://github.com
    git config --global http.https://gopkg.in.followRedirects true

jobs:
  deploy:
    environment:
      <<: *env
    working_directory: /go/src/github.com/oinume/playground-kubernetes
    docker:
      - image: docker:17.11.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
          docker_layer_caching: true
      - run:
          <<: *gitconfig
      - run:
          name: Install dependency apk packages
          command: |
            apk --no-cache add \
              bash \
              curl \
              curl-dev \
              make \
              python
      - restore_cache:
          key: google-cloud-sdk-221.0.0
      - run:
          name: "Install google-cloud-sdk"
          command: |
            ./.circleci/install-google-cloud-sdk.sh
      - save_cache:
          key: google-cloud-sdk-221.0.0
          paths:
          - /google-cloud-sdk
      - run:
          name: "Activate GCP service account"
          command: |
            echo $GCP_SERVICE_ACCOUNT_KEY | base64 -d > ./gcp-service-account-key.json
            gcloud auth activate-service-account --key-file ./gcp-service-account-key.json
      - run:
          name: "Deploy docker image to GCR"
          command: |
            TAG=$(echo "${CIRCLE_BRANCH}" | tr '._/' '-' | tr '[:upper:]' '[:lower:]')-"${CIRCLE_BUILD_NUM}"
            echo ${TAG}

            docker build --pull -f Dockerfile \
            --tag asia.gcr.io/oinume-playground-kubernetes/server:$(TAG) .

            docker tag asia.gcr.io/oinume-playground-kubernetes/server:latest asia.gcr.io/oinume-playground-kubernetes/server:${TAG}
            gcloud docker -- push asia.gcr.io/oinume-playground-kubernetes/server:latest
            gcloud docker -- push asia.gcr.io/oinume-playground-kubernetes/server:${TAG}

workflows:
  version: 2
  build-workflow:
    jobs:
    - deploy:
        filters:
          branches:
            only:
              - master
